apiVersion: v1
kind: Service
metadata:
  name: couchbase
  labels:
    name: couchbase
    role: service
spec:
  ports:
    - port: 8091
      targetPort: 8091
  selector:
    name: couchbase
    role: database