apiVersion: v1
kind: Service
metadata:
  labels:
    name: couchbase
    role: service
  name: couchbase-admin
spec:
  ports:
    - port: 8091
      targetPort: 8091
  selector:
    name: couchbase
    role: database
  type: 
    LoadBalancer
  sessionAffinity: ClientIP